Now I will train the models in my data set

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Final_cleaned_to_model.csv")
df

,ram_capacity,internal_memory,processor_brand,processor_speed,refresh_rate,primary_camera_rear,battery_capacity,has_5g,fast_charging_available,fast_charging,screen_size,num_rear_cameras,num_front_cameras,extended_memory_available,rating,num_cores,has_nfc,price
0,12.0,256.0,snapdragon,3.20,120,50.0,5000.0,True,1,65.0,6.70,3,1.0,0,89.0,8.0,True,54999
1,6.0,128.0,snapdragon,2.20,120,64.0,5000.0,True,1,65.0,6.59,3,1.0,1,81.0,8.0,False,19989
2,4.0,64.0,exynos,2.40,90,50.0,5000.0,True,1,65.0,6.60,3,1.0,1,75.0,8.0,False,16499
3,6.0,128.0,snapdragon,2.20,120,50.0,5000.0,True,1,65.0,6.55,3,1.0,1,81.0,8.0,False,14999
4,6.0,128.0,dimensity,2.60,120,108.0,5000.0,True,1,65.0,6.70,3,1.0,0,82.0,8.0,False,24999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868,8.0,128.0,snapdragon,3.00,120,64.0,5000.0,True,1,65.0,6.67,3,1.0,0,83.0,8.0,False,34990
869,6.0,128.0,snapdragon,2.20,60,48.0,5000.0,True,1,65.0,6.50,3,1.0,1,75.0,8.0,False,14990
870,8.0,256.0,dimensity,2.85,144,64.0,5080.0,True,1,65.0,6.60,3,1.0,0,85.0,8.0,True,28990
871,6.0,128.0,snapdragon,2.20,60,108.0,5000.0,True,1,65.0,6.80,3,1.0,1,80.0,8.0,True,19990
872,8.0,128.0,snapdragon,NaN,60,64.0,5000.0,True,1,65.0,6.50,3,1.0,1,74.0,8.0,False,24990

In [3]:
df.drop(columns=["num_front_cameras", "num_cores"], inplace=True)

In [4]:
df.head()

,ram_capacity,internal_memory,processor_brand,processor_speed,refresh_rate,primary_camera_rear,battery_capacity,has_5g,fast_charging_available,fast_charging,screen_size,num_rear_cameras,extended_memory_available,rating,has_nfc,price
0,12.0,256.0,snapdragon,3.2,120,50.0,5000.0,True,1,65.0,6.70,3,0,89.0,True,54999
1,6.0,128.0,snapdragon,2.2,120,64.0,5000.0,True,1,65.0,6.59,3,1,81.0,False,19989
2,4.0,64.0,exynos,2.4,90,50.0,5000.0,True,1,65.0,6.60,3,1,75.0,False,16499
3,6.0,128.0,snapdragon,2.2,120,50.0,5000.0,True,1,65.0,6.55,3,1,81.0,False,14999
4,6.0,128.0,dimensity,2.6,120,108.0,5000.0,True,1,65.0,6.70,3,0,82.0,False,24999

In [5]:
df["processor_brand"].value_counts()

processor_brand
snapdragon    361
helio         203
dimensity     176
exynos         47
unisoc         27
tiger          24
bionic         15
google          6
spreadtrum      5
unknown         3
kirin           3
sc9863a         2
fusion          1
Name: count, dtype: int64

In [6]:
for col in ["processor_speed", "battery_capacity"]:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_7868\856284362.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_7868\856284362.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [7]:
df["has_5g"] = df["has_5g"].astype(int)
df["has_nfc"] = df["has_nfc"].astype(int)

In [8]:
df["processor_brand"] = df["processor_brand"].astype("category")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 873 entries, 0 to 872
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ram_capacity               873 non-null    float64
 1   internal_memory            873 non-null    float64
 2   processor_brand            873 non-null    category
 3   processor_speed            873 non-null    float64
 4   refresh_rate               873 non-null    int64
 5   primary_camera_rear        873 non-null    float64
 6   battery_capacity           873 non-null    float64
 7   has_5g                     873 non-null    int64
 8   fast_charging_available    873 non-null    int64
 9   fast_charging              873 non-null    float64
 10  screen_size                873 non-null    float64
 11  num_rear_cameras           873 non-null    int64
 12  extended_memory_available  873 non-null    int64
 13  rating                     873 non-null    float64
 14  has_nfc                    873 non-null    int64
 15  price                      873 non-null    int64
dtypes: category(1), float64(8), int64(7)
memory usage: 103.9 KB

In [10]:
df.columns

Index(['ram_capacity', 'internal_memory', 'processor_brand', 'processor_speed',
       'refresh_rate', 'primary_camera_rear', 'battery_capacity', 'has_5g',
       'fast_charging_available', 'fast_charging', 'screen_size',
       'num_rear_cameras', 'extended_memory_available', 'rating', 'has_nfc',
       'price'],
      dtype='object')

In [11]:
df.shape

(873, 16)

In [12]:
df.isnull().sum()

ram_capacity                 0
internal_memory              0
processor_brand              0
processor_speed              0
refresh_rate                 0
primary_camera_rear          0
battery_capacity             0
has_5g                       0
fast_charging_available      0
fast_charging                0
screen_size                  0
num_rear_cameras             0
extended_memory_available    0
rating                       0
has_nfc                      0
price                        0
dtype: int64

### Starting training

In [13]:
# Separate Data and target
x = df.drop("price", axis=1)
y = df["price"]

In [14]:
# Splitting data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

Preprocessing the data

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numeric_features = x.select_dtypes(include=['int64', 'float64']).columns
categorical_features = ['processor_brand']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

Linear Regression Pipeline

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

Cross validation on train data

In [17]:
from sklearn.model_selection import cross_val_score
cv_scores_lr = cross_val_score(lr_pipeline, x_train, y_train, cv=5, scoring="r2", error_score='raise')

print("Linear Regression CV R2 Scores:", cv_scores_lr)
print("Mean CV R2:", np.mean(cv_scores_lr))

Linear Regression CV R2 Scores: [0.78872217 0.72349742 0.78267071 0.77810882 0.79824719]
Mean CV R2: 0.7742492611246821

### Knn model

In [18]:
from sklearn.neighbors import KNeighborsRegressor

knn_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', KNeighborsRegressor())
])

# Cross validation implementation
cv_scores_knn = cross_val_score(knn_pipeline,x_train,y_train,cv=5,scoring='r2')

print("KNN CV R2 Scores:", cv_scores_knn)
print("Mean CV R2:", cv_scores_knn.mean())

KNN CV R2 Scores: [0.75293119 0.62459591 0.78861311 0.70547304 0.7814587 ]
Mean CV R2: 0.7306143885592439

In the conclusion we see the Linear Regression  is giving much better prediction

### Ridge algo

In [19]:
from sklearn.linear_model import Ridge

ridge_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ("model", Ridge(alpha=1))
])

# now find the cross val score
cv_scores_ridge = cross_val_score(ridge_pipeline, x_train, y_train, cv=5, scoring="r2")

print("Ridge CV R2 Scores:", cv_scores_ridge)
print("Mean CV R2:", cv_scores_ridge.mean())

Ridge CV R2 Scores: [0.78495112 0.73795795 0.78617463 0.77507266 0.79971178]
Mean CV R2: 0.7767736285068234

### Lasso Algo

In [20]:
from sklearn.linear_model import Lasso

lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", Lasso(alpha=1))
])

cv_scores_lasso = cross_val_score(lr_pipeline, x_train, y_train, cv=5, scoring="r2")

print("Lasso CV R2 Scores:", cv_scores_lasso)
print("Mean CV R2:", cv_scores_lasso.mean())

Lasso CV R2 Scores: [0.78875426 0.71846041 0.78281518 0.77816471 0.79849197]
Mean CV R2: 0.7733373050856021

In [21]:
from sklearn.linear_model import SGDRegressor

sgd_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', SGDRegressor(max_iter=1000, learning_rate='constant', eta0=0.001, random_state=42))
])

cv_scores_sgd = cross_val_score(
    sgd_pipeline,
    x_train,
    y_train,
    cv=5,
    scoring='r2'
)

print("SGD CV R2 Scores:", cv_scores_sgd)
print("Mean CV R2:", cv_scores_sgd.mean())

sgd_pipeline.fit(x_train, y_train)

y_pred = sgd_pipeline.predict(x_test)

from sklearn.metrics import r2_score, mean_squared_error

print("Test R2:", r2_score(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(55302172.33079176))

SGD CV R2 Scores: [0.77471277 0.71540942 0.78440459 0.75208548 0.79855916]
Mean CV R2: 0.7650342830344904
Test R2: 0.729297411904154
Test MSE: 54145695.647037275
Test RMSE: 7436.543036303344

Based on cross-validation performance, Ridge Regression is selected as the final model.

In [22]:
ridge_pipeline.fit(x_train, y_train)

y_pred = ridge_pipeline.predict(x_test)

from sklearn.metrics import r2_score, mean_squared_error

print("Test R2:", r2_score(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(55302172.33079176))

Test R2: 0.7205555242975288
Test MSE: 55894240.3841173
Test RMSE: 7436.543036303344

In [23]:
# using grid search cv
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

param_grid = {
    'model__alpha': [0.01, 0.1, 1, 10, 50, 100]
}

ridge_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', Ridge())
])

grid = GridSearchCV(
    ridge_pipeline,
    param_grid,
    cv=5,
    scoring='r2'
)

grid.fit(x_train, y_train)

print("Best Alpha:", grid.best_params_)
print("Best CV R2:", grid.best_score_)

Best Alpha: {'model__alpha': 1}
Best CV R2: 0.7767736285068234

In [24]:
from sklearn.preprocessing import PolynomialFeatures

# Standardization and model
numeric_transformer = Pipeline(steps=[
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('scaler', StandardScaler())
])

# Build a new processor
preprocessor_poly = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

# New Ridge pipeline for polynomial regression

ridge_poly_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor_poly),
    ('model', Ridge(alpha=1))
])

# Cross validation
cv_scores_poly = cross_val_score(ridge_poly_pipeline,x_train,y_train,cv=5,scoring='r2')

print("Polynomial Ridge CV R2:", cv_scores_poly)
print("Mean CV R2:", cv_scores_poly.mean())

ridge_poly_pipeline.fit(x_train, y_train)

y_pred = ridge_poly_pipeline.predict(x_test)

from sklearn.metrics import r2_score, mean_squared_error

print("Test R2:", r2_score(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(55302172.33079176))

Polynomial Ridge CV R2: [0.69633854 0.75406658 0.79728526 0.80747747 0.81464938]
Mean CV R2: 0.7739634470279497
Test R2: 0.743700714449558
Test MSE: 51264759.63005499
Test RMSE: 7436.543036303344

### making Some feature engineering in the copy of the data

In [25]:
# df_fe = df.copy()

# df_fe.head()

In [26]:
# df_fe["performance_score"] = df_fe["ram_capacity"] * df_fe["processor_speed"]

# df_fe["camera_score"] = df_fe["primary_camera_rear"] * df_fe["num_rear_cameras"]

# df_fe["battery_per_inch"] = df_fe["battery_capacity"] / df_fe["screen_size"]
# df_fe["core_power"] = df_fe["num_cores"] * df_fe["processor_speed"]
# df_fe["refresh_screen"] = df_fe["refresh_rate"] * df_fe["screen_size"]

In [27]:
# X = df_fe.drop("price", axis=1)
# y = df_fe["price"]

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

# cv_scores = cross_val_score(ridge_pipeline,X_train,y_train,cv=5,scoring='r2')

# print("New CV R2:", cv_scores.mean())

### testing the our final model

We are using the Ridge regression as per our best score

In [28]:
ridge_pipeline.fit(x_train, y_train)

y_pred = ridge_pipeline.predict(x_test)

from sklearn.metrics import r2_score, mean_squared_error

print("Test R2:", r2_score(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(55302172.33079176))

Test R2: 0.7205555242975288
Test MSE: 55894240.3841173
Test RMSE: 7436.543036303344

In [29]:
columns = [
    'ram_capacity', 'internal_memory', 'processor_brand', 'processor_speed',
    'refresh_rate', 'primary_camera_rear', 'battery_capacity', 'has_5g',
    'fast_charging_available', 'fast_charging', 'screen_size',
    'num_rear_cameras','extended_memory_available',
    'rating', 'has_nfc'
]

new_data = [[
    4,        # ram_capacity (GB)
    64,      # internal_memory (GB)
    "unisoc",        # processor_brand (encoded value, e.g., 0=Snapdragon,1=MediaTek,2=Exynos...)
    2.8,      # processor_speed (GHz)
    90,      # refresh_rate (Hz)
    30,       # primary_camera_rear (MP)
    5500,     # battery_capacity (mAh)
    0,        # has_5g (1=Yes, 0=No)
    1,        # fast_charging_available (1=Yes)
    33,       # fast_charging (Watts)
    6,      # screen_size (inches)
    3,        # num_rear_cameras
    1,        # extended_memory_available (1=Yes)
    3.8,      # rating (out of 5)
    0         # has_nfc (1=Yes)
]]



new_data_df = pd.DataFrame(new_data, columns=columns)

prediction = ridge_pipeline.predict(new_data_df)
print("Predicted Price:", prediction)

Predicted Price: [15949.12486379]

In [30]:
df["processor_brand"].value_counts()

processor_brand
snapdragon    361
helio         203
dimensity     176
exynos         47
unisoc         27
tiger          24
bionic         15
google          6
spreadtrum      5
unknown         3
kirin           3
sc9863a         2
fusion          1
Name: count, dtype: int64

In [31]:
print(ridge_pipeline.named_steps['preprocessor'].transformers_)

[('num', StandardScaler(), Index(['ram_capacity', 'internal_memory', 'processor_speed', 'refresh_rate',
       'primary_camera_rear', 'battery_capacity', 'has_5g',
       'fast_charging_available', 'fast_charging', 'screen_size',
       'num_rear_cameras', 'extended_memory_available', 'rating', 'has_nfc'],
      dtype='object')), ('cat', OneHotEncoder(handle_unknown='ignore'), ['processor_brand'])]

### Cleaned pipeline code
### Only Ridge Regression Apply

In [32]:
# Separate Data and target
df_fe = df.copy(deep=True)
x = df_fe.drop("price", axis=1)
y = df_fe["price"]

# Splitting data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numeric_features = x.select_dtypes(include=['int64', 'float64']).columns
categorical_features = ['processor_brand']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

from sklearn.linear_model import Ridge

ridge_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ("model", Ridge(alpha=1))
])

# now find the cross val score
cv_scores_ridge = cross_val_score(ridge_pipeline, x_train, y_train, cv=5, scoring="r2")

print("Ridge CV R2 Scores:", cv_scores_ridge)
print("Mean CV R2:", cv_scores_ridge.mean())

ridge_pipeline.fit(x_train, y_train)

y_pred = ridge_pipeline.predict(x_test)

from sklearn.metrics import r2_score, mean_squared_error

print("Test R2:", r2_score(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(55302172.33079176))

Ridge CV R2 Scores: [0.78495112 0.73795795 0.78617463 0.77507266 0.79971178]
Mean CV R2: 0.7767736285068234
Test R2: 0.7205555242975288
Test MSE: 55894240.3841173
Test RMSE: 7436.543036303344

### Polynomial and Ridge both algo are apply

In [33]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_squared_error



#  Deep Copy of the original data

df_fe = df.copy(deep=True)

X = df_fe.drop("price", axis=1)
y = df_fe["price"]


# Train Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# Feature Selection

numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = ['processor_brand']


# Numeric Pipeline
numeric_pipeline = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, include_bias=False))
])


# Column Transformer 
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_pipeline, numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)


# Final Pipeline
poly_ridge_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', Ridge(alpha=1))
])


# Cross Validation
cv_scores = cross_val_score(
    poly_ridge_pipeline,
    X_train,
    y_train,
    cv=5,
    scoring="r2"
)

print("CV R2 Scores:", cv_scores)
print("Mean CV R2:", cv_scores.mean())
print("Std CV R2:", cv_scores.std())


# Train Final Model
poly_ridge_pipeline.fit(X_train, y_train)

y_pred = poly_ridge_pipeline.predict(X_test)

print("\nTest R2:", r2_score(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))


# SAVE MODEL USING JOBLIB

joblib.dump(poly_ridge_pipeline, "smartphone_price_model.pkl")

print("\n Model saved as laptop_price_model.pkl")


# Save Feature Columns

joblib.dump(list(X.columns), "model_features.pkl")

print(" Feature columns saved as model_features.pkl")

CV R2 Scores: [-0.00285639  0.67430877  0.76050138  0.7439781   0.81085612]
Mean CV R2: 0.5973575972803387
Std CV R2: 0.30327327595790654

Test R2: 0.7371079586726178
Test MSE: 52583436.892376035
Test RMSE: 7251.443779853502

 Model saved as laptop_price_model.pkl
 Feature columns saved as model_features.pkl

In [34]:
df.columns

Index(['ram_capacity', 'internal_memory', 'processor_brand', 'processor_speed',
       'refresh_rate', 'primary_camera_rear', 'battery_capacity', 'has_5g',
       'fast_charging_available', 'fast_charging', 'screen_size',
       'num_rear_cameras', 'extended_memory_available', 'rating', 'has_nfc',
       'price'],
      dtype='object')

num_cores
8.0    822
4.0     36
6.0     15
Name: count, dtype: int64